# Generated by Django 5.2.9 on 2026-02-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geminianalysis',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
