# Generated by Django 5.2.9 on 2026-02-10 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_geminianalysis_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedimage',
            name='image',
            field=models.TextField(),
        ),
    ]
