# Generated by Django 5.2.9 on 2026-02-10 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_uploadedimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='students',
            name='external_id',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='external_id',
        ),
    ]
